from User_Auth.database import db
from datetime import datetime 
from sqlalchemy.dialects.postgresql import ARRAY
# table for holding all recipes generated by our system on behalf of another user
class SavedRecipe(db.Model):
    __tablename__ = 'generated_recipes'

    meal_id = db.Column(db.String(80), primary_key=True, nullable=False)
    
    # Foreign key to existing users table
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)

    # Core recipe fields
    recipe_name = db.Column(db.String(255), nullable=False)
    meal_type = db.Column(db.String(40), nullable=False)

    instructions = db.Column(db.Text, nullable=True)
    ingredients = db.Column(db.Text, nullable=True)
    #health_info = db.Column(db.Text, nullable=True)
    carbs=db.Column(db.Integer,nullable=True)
    fats=db.Column(db.Integer,nullable=True)
    protein=db.Column(db.Integer,nullable=True)
    created_on = db.Column(db.DateTime, default=datetime.utcnow, nullable=False)



    def __repr__(self):

        return f" Recipe: {self.recipe_name} Saved for user (User {self.user_id})>"


# used to generate unique recipe Ids to help with saviing meals in the front end
def generatemealIDs(userID,nRecipes):
    # SavedRecipe.__table__.drop(db)
    # SavedRecipe.__table__.create(db)
    # db.create_all()
    recipe_count = SavedRecipe.query.filter_by(user_id=userID).count()
    ids=[]
    
    for x in range(recipe_count+1,((recipe_count+1)+nRecipes)):
        ids.append(f"{userID}_{x}")
    return ids


# function to add newly generated meals to database
def saveNewMeals(userID,newMeals):
    # print("MEALS",newMeals)
    # upload each meal to the database
    for meal in newMeals["meals"]:


        # Tess: Commented this out for now to fix the nested f-string error ↓
        # create new meal object
        #newMeal=SavedRecipe(user_id=userID,meal_id=meal["id"],recipe_name=meal["name"],meal_type=meal["mealType"],
        #instructions=f"{meal["instructions"]}",ingredients=f"{meal["ingredients"]}",carbs=meal["carbs"],
        #fats=meal["fats"],protein=meal["protein"])

                # create new meal object (use .get and avoid nested f-strings)
        newMeal = SavedRecipe(
            user_id=userID,
            meal_id=meal.get("id"),
            recipe_name=meal.get("name"),
            meal_type=meal.get("mealType"),
            instructions=str(meal.get("instructions")) if meal.get("instructions") is not None else None,
            ingredients=str(meal.get("ingredients")) if meal.get("ingredients") is not None else None,
            carbs=meal.get("carbs"),
            fats=meal.get("fats"),
            protein=meal.get("protein"),
        )

        db.session.add(newMeal)
        db.session.commit()



